name: Main

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: borales/actions-yarn@v2.3.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: yarn
            - run: yarn run test
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: borales/actions-yarn@v2.3.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: yarn
            - run: yarn run compile
    coverage:
        needs: [test]
        name: coverage
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                  node-version: '12'
            - uses: borales/actions-yarn@v2.3.0
            - run: yarn install
            - uses: paambaati/codeclimate-action@v2.2.4
              env:
                  CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TOKEN }}
              with:
                  coverageCommand: yarn coverage
