name: Main

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: borales/actions-yarn@v2.3.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: yarn
            - run: yarn run test --if-present
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: borales/actions-yarn@v2.3.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: yarn
            - run: yarn run compile --if-present
